### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by troelskn** [minciue/cloudprint#8]
The current latest published gem has a dependency on oauth2 `0.8.0`. This is incompatible with the latest Rails.

It seems to work fine if I change the dependency to `1.1.0`. Could you update and publish a new gem version?

**Comment by minciue** [comment]
Just to be a bit more cautious, I'd like to have a dependency of `>= 1.0.0`. Do you see any reason why that wouldn't work?

**Comment by minciue** [comment]
I've released 0.3.0 with an updated dependency (along with a couple of other minor things). I'm closing this for now but feel free to reopen if there's any dependecy issue.

**Comment by troelskn** [comment]
That sounds fine. `1.1.0` is the first version that updates its dependency from rack `1.2`, which is the culprit, but with `>= 1.0.0` rails should be able to resolve correctly to `1.1.0`.
